import { createBrowserRouter } from "react-router-dom";
import { AppLayout } from "@/layouts/AppLayout";
import { lazyElement } from "@/routes/lazyElement";
import { paths } from "@/routes/paths";

const page = {
  about: () => lazyElement(() => import("@/pages/AboutPage"), "AboutPage"),
  alerts: () => lazyElement(() => import("@/pages/AlertsPage"), "AlertsPage"),
  analytics: () => lazyElement(() => import("@/pages/AnalyticsPage"), "AnalyticsPage"),
  architecture: () => lazyElement(() => import("@/pages/ArchitecturePage"), "ArchitecturePage"),
  aiPrediction: () => lazyElement(() => import("@/pages/AiPredictionPage"), "AiPredictionPage"),
  dashboard: () => lazyElement(() => import("@/pages/DashboardPage"), "DashboardPage"),
  digitalTwin: () => lazyElement(() => import("@/pages/DigitalTwinPage"), "DigitalTwinPage"),
  documentation: () => lazyElement(() => import("@/pages/DocumentationPage"), "DocumentationPage"),
  landing: () => lazyElement(() => import("@/pages/LandingPage"), "LandingPage"),
  liveMap: () => lazyElement(() => import("@/pages/LiveMapPage"), "LiveMapPage"),
  myDevices: () => lazyElement(() => import("@/pages/MyDevicesPage"), "MyDevicesPage"),
  login: () => lazyElement(() => import("@/pages/onboarding/LoginPage"), "LoginPage"),
  nodes: () => lazyElement(() => import("@/pages/NodesPage"), "NodesPage"),
  notFound: () => lazyElement(() => import("@/pages/NotFoundPage"), "NotFoundPage"),
  notifications: () => lazyElement(() => import("@/pages/NotificationsPage"), "NotificationsPage"),
  otp: () => lazyElement(() => import("@/pages/onboarding/OtpPage"), "OtpPage"),
  approvalWorkflow: () => lazyElement(() => import("@/pages/onboarding/ApprovalWorkflowPage"), "ApprovalWorkflowPage"),
  deviceRegistration: () => lazyElement(() => import("@/pages/onboarding/DeviceRegistrationPage"), "DeviceRegistrationPage"),
  emergencyContact: () => lazyElement(() => import("@/pages/onboarding/EmergencyContactPage"), "EmergencyContactPage"),
  locationSelection: () => lazyElement(() => import("@/pages/onboarding/LocationSelectionPage"), "LocationSelectionPage"),
  profileSetup: () => lazyElement(() => import("@/pages/onboarding/ProfileSetupPage"), "ProfileSetupPage"),
  register: () => lazyElement(() => import("@/pages/onboarding/RegisterPage"), "RegisterPage"),
  roleSelection: () => lazyElement(() => import("@/pages/onboarding/RoleSelectionPage"), "RoleSelectionPage"),
  roleRegistration: () => lazyElement(() => import("@/pages/onboarding/RoleRegistrationPage"), "RoleRegistrationPage"),
  settings: () => lazyElement(() => import("@/pages/SettingsPage"), "SettingsPage"),
  simulation: () => lazyElement(() => import("@/pages/SimulationPage"), "SimulationPage"),
  userProfile: () => lazyElement(() => import("@/pages/UserProfilePage"), "UserProfilePage"),
  weather: () => lazyElement(() => import("@/pages/WeatherPage"), "WeatherPage"),
};

export const appRouter = createBrowserRouter([
  { path: paths.register, element: page.register(), errorElement: page.notFound() },
  { path: paths.login, element: page.login(), errorElement: page.notFound() },
  { path: paths.otp, element: page.otp(), errorElement: page.notFound() },
  { path: paths.roleSelection, element: page.roleSelection(), errorElement: page.notFound() },
  { path: paths.roleRegistration, element: page.roleRegistration(), errorElement: page.notFound() },
  { path: paths.profileSetup, element: page.profileSetup(), errorElement: page.notFound() },
  { path: paths.locationSelection, element: page.locationSelection(), errorElement: page.notFound() },
  { path: paths.emergencyContact, element: page.emergencyContact(), errorElement: page.notFound() },
  { path: paths.deviceRegistration, element: page.deviceRegistration(), errorElement: page.notFound() },
  { path: paths.approvalWorkflow, element: page.approvalWorkflow(), errorElement: page.notFound() },
  {
    path: paths.landing,
    element: <AppLayout />,
    errorElement: page.notFound(),
    children: [
      { index: true, element: page.landing() },
      { path: "dashboard", element: page.dashboard() },
      { path: "live-map", element: page.liveMap() },
      { path: "nodes", element: page.nodes() },
      { path: "weather", element: page.weather() },
      { path: "analytics", element: page.analytics() },
      { path: "ai-prediction", element: page.aiPrediction() },
      { path: "alerts", element: page.alerts() },
      { path: "digital-twin", element: page.digitalTwin() },
      { path: "simulation", element: page.simulation() },
      { path: "architecture", element: page.architecture() },
      { path: "documentation", element: page.documentation() },
      { path: "settings", element: page.settings() },
      { path: "profile", element: page.userProfile() },
      { path: "notifications", element: page.notifications() },
      { path: "my-devices", element: page.myDevices() },
      { path: "about", element: page.about() },
    ],
  },
  { path: "*", element: page.notFound() },
]);
