import {
  Activity,
  BatteryCharging,
  BrainCircuit,
  CloudRain,
  Cpu,
  HardDrive,
  RadioTower,
  Router,
  Satellite,
  Signal,
} from "lucide-react";
import type { DashboardData } from "@/features/dashboard/types/dashboard.types";

export const dashboardMockData: DashboardData = {
  header: {
    missionTime: "13 Jul 2026, 16:42 BDT",
    operator: "EcoMesh Mission Control",
    region: "Khulna, Satkhira, Barguna coastal belt",
    subtitle:
      "Operational intelligence for self-healing LoRa mesh nodes, coastal weather telemetry, edge-AI predictions, and disaster response readiness.",
    syncState: "Live sync",
    title: "Enterprise IoT Dashboard",
  },
  stats: [
    {
      detail: "118 of 128 LoRa nodes are reporting within SLA.",
      icon: RadioTower,
      id: "active-nodes",
      label: "Active Nodes",
      progress: 92,
      status: "online",
      tone: "emerald",
      unit: "/128",
      value: 118,
    },
    {
      detail: "Gateway GW-03 is operating in conservation mode.",
      icon: Router,
      id: "gateways",
      label: "Gateways",
      progress: 86,
      status: "degraded",
      tone: "amber",
      unit: "online",
      value: 6,
    },
    {
      detail: "Median uplink quality across coastal clusters.",
      icon: Satellite,
      id: "packet-delivery",
      label: "Packet Delivery",
      progress: 97.6,
      status: "online",
      tone: "cyan",
      unit: "%",
      value: 97.6,
    },
    {
      detail: "Autonomous route recovery after packet jitter spike.",
      icon: Cpu,
      id: "mesh-recovery",
      label: "Mesh Recovery",
      status: "healing",
      tone: "violet",
      unit: "sec",
      value: 4.8,
    },
    {
      detail: "18 nodes are below the preferred battery reserve.",
      icon: BatteryCharging,
      id: "battery",
      label: "Battery Reserve",
      progress: 76,
      status: "stable",
      tone: "emerald",
      unit: "%",
      value: 76,
    },
    {
      detail: "Buffered locally for intermittent backhaul windows.",
      icon: HardDrive,
      id: "data-buffer",
      label: "Data Buffer",
      progress: 64,
      status: "stable",
      tone: "slate",
      unit: "GB",
      value: 12.4,
    },
  ],
  weather: {
    condition: "Monsoon cell approaching",
    narrative: "Rain and wind signatures are rising across the southern cluster while pressure continues to fall near the coastal belt.",
    riskIndex: 72,
    metrics: [
      { id: "temperature", label: "Temperature", tone: "amber", trend: "+1.2", unit: "C", value: 31.8 },
      { id: "humidity", label: "Humidity", tone: "cyan", trend: "+4", unit: "%", value: 84 },
      { id: "pressure", label: "Pressure", tone: "violet", trend: "-6", unit: "hPa", value: 1002 },
      { id: "wind", label: "Wind", tone: "cyan", trend: "+9", unit: "km/h", value: 38 },
      { id: "rain", label: "Rainfall", tone: "emerald", trend: "+18", unit: "mm", value: 62 },
    ],
  },
  clusters: [
    { degraded: 4, id: "satkhira", latencyMs: 172, name: "Satkhira", offline: 1, online: 42, packetDelivery: 98.2 },
    { degraded: 3, id: "khulna", latencyMs: 188, name: "Khulna", offline: 2, online: 36, packetDelivery: 96.9 },
    { degraded: 2, id: "barguna", latencyMs: 204, name: "Barguna", offline: 1, online: 40, packetDelivery: 97.4 },
  ],
  alerts: [
    { confidence: 92, id: "ALT-2048", severity: "critical", timeAgo: "2 min ago", title: "Cyclone-band wind spike", zone: "Barguna South" },
    { confidence: 81, id: "ALT-2047", severity: "warning", timeAgo: "8 min ago", title: "Gateway packet jitter", zone: "Koyra Relay" },
    { confidence: 74, id: "ALT-2046", severity: "info", timeAgo: "17 min ago", title: "Twin scenario completed", zone: "Simulation Core" },
  ],
  activities: [
    {
      description: "Self-healing route stabilized packet delivery after RSSI degradation.",
      id: "ACT-01",
      status: "healing",
      time: "16:41",
      title: "Node SK-042 rerouted via SK-037",
    },
    {
      description: "Edge model identified rainfall behavior outside the seven-day baseline.",
      id: "ACT-02",
      status: "online",
      time: "16:36",
      title: "Rainfall anomaly detected",
    },
    {
      description: "Gateway switched to reduced-power mode while retaining alert priority.",
      id: "ACT-03",
      status: "degraded",
      time: "16:22",
      title: "GW-03 conservation mode",
    },
    {
      description: "Digital twin flood scenario exported to the command dashboard.",
      id: "ACT-04",
      status: "stable",
      time: "16:10",
      title: "Simulation artifact synced",
    },
  ],
  mapEntities: [
    { id: "GW-01", label: "Satkhira Gateway", status: "online", type: "gateway", x: 24, y: 42 },
    { id: "LN-037", label: "Koyra Node", status: "healing", type: "node", x: 42, y: 55 },
    { id: "BOAT-17", label: "Rescue Boat", status: "stable", type: "boat", x: 62, y: 68 },
    { id: "SHT-04", label: "Shelter Hub", status: "online", type: "shelter", x: 76, y: 40 },
    { id: "GW-03", label: "Barguna Relay", status: "degraded", type: "gateway", x: 68, y: 28 },
  ],
};

export const dashboardPrediction = {
  confidence: 89,
  icon: BrainCircuit,
  label: "Localized flooding likely within 6 hours",
  recommendation: "Preserve gateway power, increase sensor sampling in Satkhira, and pre-stage community alert routes.",
};

export const dashboardSystemSignals = [
  { icon: Activity, label: "Telemetry ingest", status: "online", value: 98 },
  { icon: Signal, label: "Signal quality", status: "stable", value: 91 },
  { icon: CloudRain, label: "Rain model", status: "degraded", value: 74 },
] as const;
